import type { Metadata } from "next";
import "./globals.css";
// import { Navbar } from "@/components/ui/resizable-navbar";
import Navbars from "@/components/Navbar";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "CodeArena",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-black text-white min-h-screen">
        <Navbars />
        {children}
        {/* <div className="text-center  max-w-7xl mx-auto"> */}
          <Footer />
        {/* </div> */}
      </body>
    </html>
  );
}
