import type { Metadata } from "next";
import "./globals.css";
// import { Navbar } from "@/components/ui/resizable-navbar";
import Navbars from "@/components/Navbar";
// import Footer from "@/components/Footer";
import { ShootingStars } from "@/components/ui/shooting-stars";
import { StarsBackground } from "@/components/ui/stars-background";
// import { Providers } from "./providers";

export const metadata: Metadata = {
  title: "CodeArena",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-black text-white min-h-screen flex flex-col">
        <Navbars />
        <main className="flex-1">{children}</main>
        {/* <Footer /> */}
        <ShootingStars className=""/>
        <StarsBackground className=""/>
      </body>
    </html>
  );
}
